# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
tab = [
    {BaseLine: "",
Email: "s.marthelot@19-hz.com",
Fondateur1: "Stephan Marthelot",
Fondateur2: "Sophea Sok",
Fondateur3: "",
Fondateur4: "",
Nom: "19Hz",
NombreDeCollaborateurs: "",
Pitch: "Nous proposons des solutions novatrices pour accompagner les entreprises à intégrer la dimension design au coeur de leur innovation.",
Secteur: "Education",
SiteWeb: "",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "edouard@allum.ee",
Fondateur1: "Edouard Ferrari",
Fondateur2: "Patrick Hennion",
Fondateur3: "",
Fondateur4: "",
Nom: "Allumee",
NombreDeCollaborateurs: "",
Pitch: "Chez Allumee nous voulons émerveiller le public en créant des spectacles innovants et créatifs en s’appuyant sur les nouvelles technologies et notamment les drones. Nous proposons des solutions faciles à utiliser pour nos clients, à fin d'accélérer l'émergence des spectacles de drones en France et en Europe. Chaque drone est un point lumineux et va se positionner suivant un scénario. Cet ensemble de drones permet d'afficher des formes simples, tel que des textes ou des logos, des formes complexes (modèle 3D) ou des formes animées.",
Secteur: "",
SiteWeb: "http://www.allum.ee/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Nous veillons sur ceux qui veillent sur vous",
Email: "contact@aum.bio",
Fondateur1: "Marc Riedel",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Aum Biosync",
NombreDeCollaborateurs: "",
Pitch: "Etre performant 24h/7j n’est pas à la portée de tous. AUM Biosync se base sur une connaissance fine des rythmes biologiques pour construire une horlogerie numérique personnalisée des moments de performances optimales ou de vulnérabilités des professionnels « always-on », et leur permet d’exprimer tout leur potentiel, au bon moment.",
Secteur: "Santé",
SiteWeb: "https://aum.bio/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Les places en crèches, maintenant !",
  Email: "nicolas@babily.fr",
  Fondateur1: "Nicolas Lorut",
  Fondateur2: "",
  Fondateur3: "",
  Fondateur4: "",
  Nom: "Babily",
  NombreDeCollaborateurs: "",
  Pitch: "Babily offre une accessibilité inédite aux disponibilités en crèches en temps réel, via sa web app, et par tout canal pratique.",
  Secteur: "E-commerce",
  SiteWeb: "www.babily.fr",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Découvrez des stratégies digitales d'experts Sales, Marketing & Social Media chaque semaine",
  Email: "",
  Fondateur1: "Paul de Castelbajac",
  Fondateur2: "Victor Linder",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Behind The Skills",
  NombreDeCollaborateurs: "",
  Pitch: "Behind the Skills te fait découvrir chaque semaine des “hacks”, trucs et astuces d’experts Sales et Marketing pour que tu puisses monter en compétence, efficacement. On va partir de problématiques d’experts pour te livrer un peu de leur recette magique afin que tu puisses exploiter leur solutions et générer un réel impact sur ton business avec des actions concrètes.",
  Secteur: "Media",
  SiteWeb: "https://www.linkedin.com/company/behind-the-skills/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La solution pour les personnes à mobilité réduite",
Email: "julien@benur.net",
Fondateur1: "Joseph Mignozzi",
Fondateur2: "Steven Denton",
Fondateur3: "",
Fondateur4: "",
Nom: "Benur",
NombreDeCollaborateurs: "",
Pitch: "Benur est une nouvelle solution de mobilité pour toutes les personnes à mobilité réduite. C’est un nouveau concept de tricycle à assistance électrique, permettant à tous de gagner en autonomie, en liberté, en mobilité.",
Secteur: "Transport & Mobilité",
SiteWeb: "https://www.projet-benur.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Votre logiciel de soins pharmaceutiques",
  Email: "contact@bimedoc.com",
  Fondateur1: "Pierre Renaudin",
  Fondateur2: "Thomas Dauvet",
  Fondateur3: "Thomas Emery",
  Fondateur4: "Ron Danenberg",

  Nom: "Bimedoc",
  NombreDeCollaborateurs: "",
  Pitch: "Bimedoc est une application web d’aide à la réalisation des activités d’accompagnement pharmaceutique et d’optimisation thérapeutique en pharmacie d’officine et en établissement de santé incluant un algorithme d’aide à la décision.",
  Secteur: "Santé",
  SiteWeb: "https://www.bimedoc.com/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La conteuse avec la voix des proches",
  Email: "hello@mybookinou.com",
  Fondateur1: "Vincent Gunther",
  Fondateur2: "Guillaume Chanteloube",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Bookinou",
  NombreDeCollaborateurs: "",
  Pitch: "La conteuse Bookinou aide les parents à donner le goût de la lecture aux enfants en remplaçant les écrans par des livres ! Grâce à Bookinou, les enfants peuvent écouter leurs histoires préférées, enregistrées par ses proches.",
  Secteur: "E-commerce",
  SiteWeb: "www.mybookinou.com",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "iYu Care for you",
  Email: "contact@capsix-robotics.com",
  Fondateur1: "Carole Eyssautier",
  Fondateur2: "François Eyssautier",
  Fondateur3: "Stéphane Rollet",
  Fondateur4: "",

  Nom: "Capsix Robotics",
  NombreDeCollaborateurs: "",
  Pitch:"Capsix est une startup Lyonnaise qui a développé iYU Pro®, une solution de détente musculaire permettant au collaborateur d’accéder à un état de lâcher-prise corporel et mental. Toujours disponible, autonome, personnalisée et facilement accessible, iYU Pro® est basée sur des protocoles définis par des professionnels pour une pause régénérante et bienfaisante.",
  Secteur: "Santé",
  SiteWeb: "https://capsix-robotics.com/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
}, {

  BaseLine: "Booster de bonheur",
  Email: "hello@carot.fr",
  Fondateur1: "Colini Casini",
  Fondateur2: "Pierre-Yves Coeurdevey",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Carot",
  NombreDeCollaborateurs: "",
  Pitch: "Nous concevons des repas frais pour sportifs que nous distribuons dans des Corners connectés 100% autonomes implantés à l’interieur des structures sportives ou des entreprises. Nous livrons également nos repas sur les spot outdoor où en entreprise après une séance de sport collective. Enfin, nous proposons un service traiteur innovant.",
  Secteur: "Alimentation",
  SiteWeb: "https://carot.fr/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La première plateforme qui te permet de changer de box chaque mois. ",
  Email: "contact@chooseyourbox.co",
  Fondateur1: "Pauline Lupion",
  Fondateur2: "Michaël Abramczuk",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Choose Your Box",
  NombreDeCollaborateurs: "",
  Pitch: "Choose Your Box est la première plateforme d’abonnement qui te permet de changer de box d’un mois à l’autre en 1 clic. Chaque mois, tu as jusqu’au 27 inclus pour faire ton choix parmi le catalogue qui recense déjà plus d’une cinquantaine de box dans de nombreuses catégories : beauté, vin, mode, lifestyle, sport ou épicerie, il y en a pour tous les goûts.",
  Secteur: "E-commerce",
  SiteWeb: "www.chooseyourbox.co",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Ultimate Stress Measurement",
  Email: "contact@codesna.com",
  Fondateur1: "Marc Latouche",
  Fondateur2: "Vasile Zoicas",
  Fondateur3: "François Le Faucheur",
  Fondateur4: "",

  Nom: "Codesna",
  NombreDeCollaborateurs: "",
  Pitch: "Codesna a développé des solutions innovantes et brevetées permettant d’évaluer de manière scientifique une présence de stress chronique. L’objectif est d’aider les personnes à évaluer et gérer un stress chronique dans une approche de prévention et de réduire les risques et les coûts des pathologies qui sont associées.",
  Secteur: "Santé",
  SiteWeb: "https://www.codesna.com/fr/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
}, {
  BaseLine: "Editeur logiciel et cabinet de conseil spécialisé dans le pilotage de l'activité viticole",
Email: "contact@daliasoft.com",
Fondateur1: "Sabrina Sallouh",
Fondateur2: "Chams ",
Fondateur3: "",
Fondateur4: "",
Nom: "Daliasoft",
NombreDeCollaborateurs: "",
Pitch: "Vignerons, négociants et coopératives, exploitez avec simplicité toute la richesse de vos données. Une solution de Business Intelligence clé en main qui vous donne de la visibilité sur le déroulement de votre activité et vous permet d’améliorer votre prise de décision",
Secteur: "Alimentation",
SiteWeb: "http://www.daliasoft.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Animez les données de vos restaurants",
Email: "contact@dvore.fr",
Fondateur1: "Richard Barone",
Fondateur2: "Colin Saboul",
Fondateur3: "",
Fondateur4: "",
Nom: "Dvore",
NombreDeCollaborateurs: "",
Pitch: "Solution Saas de pilotage décisionnel pour améliorer la rentabilité des groupes de restaurants. Automatisation de tableaux de reporting intelligents en temps réel ; algorithme de prévision des ventes ; animation réseaux par challenges des points de vente.",
Secteur: "Alimentation",
SiteWeb: "https://www.dvore.fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "contact@energiency.com",
Fondateur1: "Arnaud Legrand",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Energiency",
NombreDeCollaborateurs: "",
Pitch: "Energiency automatise l'analyse énergétique grâce à une technologie basée sur l'intelligence artificielle et dédiée aux industries.",
Secteur: "Transition écologique",
SiteWeb: "https://www.energiency.com/fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "info@enertiv.com",
Fondateur1: "Connell McGill",
Fondateur2: "Pavel Khodorkovskiy",
Fondateur3: "",
Fondateur4: "",
Nom: "Enertiv",
NombreDeCollaborateurs: "",
Pitch: "Nous transformons les données du bâtiment en actif pour les portefeuilles immobiliers commerciaux",
Secteur: "Transformation digitale",
SiteWeb: "http://www.enertiv.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "L'outil de financement pour les professionnels de l'automobile",
  Email: "bonjour@finnocar.com",
  Fondateur1: "Yassine Tazi",
  Fondateur2: "",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Finnocar",
  NombreDeCollaborateurs: "",
  Pitch: "FinnoCar transforme la relation client des points de vente et sites web automobiles en offrant à leurs clients une expérience de financement digitale et instantanée. Pour la première fois, les acheteurs peuvent effectuer leur demande de financement et toutes les démarches nécessaires en ligne. FinnoCar permet aux clients des vendeurs automobiles d’accéder instantanément aux offres de plusieurs banques pour trouver les meilleures offres du marché.",
  Secteur: "Transformation digitale",
  SiteWeb: "https://www.finnocar.com/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
  Email: "production@franceplay.net",
  Fondateur1: "Marc Bechet",
  Fondateur2: "",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "FrancePlay",
  NombreDeCollaborateurs: "",
  Pitch: "FrancePlay.Tv est la plateforme TV du tourisme 100% vidéo, 100% collaborative et 100 % France !",
  Secteur: "Media",
  SiteWeb: "https://franceplay.tv/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Gérez l'hétérogénéité des compétences de vos apprenants en cours de français langue étrangère.",
Email: "hello@frello.fr",
Fondateur1: "Théo Dumarski",
Fondateur2: "Louis Rapilly",
Fondateur3: "",
Fondateur4: "",
Nom: "Frello",
NombreDeCollaborateurs: "",
Pitch: "Frello veut permettre aux professeurs de français qui donnent des cours à des étrangers de s’adapter aux difficultés, au niveau de départ et à la façon d’apprendre de chaque apprenant.",
Secteur: "Education",
SiteWeb: "https://www.frello.fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Ton orientation pas comme les autres",
Email: "charly@hello-charly.com",
Fondateur1: "Fatma Chouaieb",
Fondateur2: "Laurent Deambrogio",
Fondateur3: "",
Fondateur4: "",
Nom: "Hello Charly",
NombreDeCollaborateurs: "",
Pitch: "Hello Charly conçoit et développe des chatbots vocationnels 100% digitaux pour que chacun puisse trouver sa voie de façon inspirante et personnalisée.",
Secteur: "Education",
SiteWeb: "https://hello-charly.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Nous sommes convaincus que votre projet mérite de voir le jour",
Email: "",
Fondateur1: "Boris Laval",
Fondateur2: "Cassandra Martins-Almeida",
Fondateur3: "",
Fondateur4: "",
Nom: "ID Value",
NombreDeCollaborateurs: "",
Pitch: "Plateforme de mise en relation entre porteur de projet et public cible",
Secteur: "Transformation digitale",
SiteWeb: "",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Decentralized cloud computing",
Email: "contact@iex.ec",
Fondateur1: "Gilles Fedak",
Fondateur2: "Haiwu He",
Fondateur3: "",
Fondateur4: "",

Nom: "iExec",
NombreDeCollaborateurs: "",
Pitch: "iExec crée un réseau de fournisseurs qui forment une infrastructure Cloud virtuel. Vous pouvez accéder à cette infrastructure décentralisée soit en exécutant vos applications, soit en louant vos ressources et donc en faisant partie des fournisseurs.",
Secteur: "Transformation digitale",
SiteWeb: "https://iex.ec/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Learn French with the news",
Email: "contact@ilini.com",
Fondateur1: "Benjamin Rey",
Fondateur2: "Adeline Salomé",
Fondateur3: "",
Fondateur4: "",

Nom: "Ilini",
NombreDeCollaborateurs: "",
Pitch: "Ilini permet aux étrangers d’apprendre le français de manière naturelle en regardant des vidéos interactives tirées des médias.",
Secteur: "Education",
SiteWeb: "www.ilini.com",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "matt@inokufu.com",
Fondateur1: "Matthieu Sonnati",
Fondateur2: "Benjamin Parmentier",
Fondateur3: "",
Fondateur4: "",

Nom: "Inokufu",
NombreDeCollaborateurs: "4",
Pitch: "Inokufu est une entreprise Edtech spécialisée dans le traitement des données dans le secteur de la formation professionnelle et de l'enseignement supérieur. Nous fournissons à nos clients, organismes de formations ou éditeurs EdTech, des informations en temps réel sur les évolutions de leur marché et des services de recommendation de contenu éducatif de qualité.",
Secteur: "Education",
SiteWeb: "https://www.inokufu.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Navigations d'exception",
Email: "contact@ishua.fr",
Fondateur1: "Julien Boisson",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Ishua",
NombreDeCollaborateurs: "",
Pitch: "Ishua, c’est un “Sailing club” qui propose des croisières en voiliers et de la formation à la navigation, sur des voiliers modernes et confortables, vers des destinations de rêve. Et qui consacre 30% de son activité à des projets écologiques et vertueux.",
Secteur: "Transport & Mobilité",
SiteWeb: "www.ishua.eu",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Solutions RH pour une affectation géo optimisée",
Email: "",
Fondateur1: "Alban Castaing",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Jeekan",
NombreDeCollaborateurs: "",
Pitch: "Jeekan est une startup de l'économie sociale et solidaire. Nous aidons les DRH à réduire, voire éviter,  les déplacements liés au travail de leurs collaborateurs grâce à notre plateforme d'analyse et d'optimisation des trajets. Notre mission est de faciliter le quotidien des collaborateurs en réduisant les mobilités liées au travail.",
Secteur: "RH",
SiteWeb: "https://www.jeekan.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "hello@jenji.io",
Fondateur1: "Pierre Queinnec",
Fondateur2: "Nicolas André",
Fondateur3: "",
Fondateur4: "",
Nom: "Jenji",
NombreDeCollaborateurs: "",
Pitch: "Jenji est la première solution pan-européenne qui automatise la gestion des dépenses professionnelles grâce à l'Intelligence Artificielle. Elle permet aux entreprises de gérer en temps réel les frais professionnels de leurs collaborateurs.",
Secteur: "Transformation digitale",
SiteWeb: "https://jenji.io/fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "LAfricaMobile est leader dans la fourniture de solutions web et mobiles innovantes en Afrique.",
  Email: "contact@lafricamobile.com",
  Fondateur1: "Malick Diouf",
  Fondateur2: "",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "LAfricaMobile",
  NombreDeCollaborateurs: "",
  Pitch: "Fort de son expertise en développement et en connectique opérateur, LAfricaMobile accompagne ses clients, particulièrement les média et les éditeurs, à proposer ou monétiser leurs services mobiles en Afrique et à destination de la diaspora africaine dans le monde entier.",
  Secteur: "Transformation digitale",
  SiteWeb: "https://lafricamobile.com/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La bonne occasion d'acheter sa voiture entre particuliers",
Email: "vincent@lepiston.fr",
Fondateur1: "Vincent Dreyfus",
Fondateur2: "Constantin Eliard",
Fondateur3: "",
Fondateur4: "",
Nom: "Le Piston",
NombreDeCollaborateurs: "",
Pitch: "Notre proposition de valeur est de gérer, sécuriser et accélérer la vente de voitures d’occasion entre particuliers et pour le compte d’entreprises, le tout au meilleur prix et en offrant une expérience client irréprochable.",
Secteur: "Transport & Mobilité",
SiteWeb: "https://lepiston.fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La prévention santé devient connectée",
Email: "contact@life-xtend.fr",
Fondateur1: "Hervé Touré",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Lifextend",
NombreDeCollaborateurs: "",
Pitch: "Lifextend est une solution de prévention santé visant à «optimiser sa santé et son bien-être» grâce à une analyse à 360 degrés des risques santé selon différents thèmes: environnement, stress, alimentation, ascendance.",
Secteur: "Santé",
SiteWeb: "https://life-xtend.fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Des services e-santé innovants pour vos usagers et vos collaborateurs",
Email: "contact@lilismart.com",
Fondateur1: "Vincent Thery",
Fondateur2: "Aymeric Garnier",
Fondateur3: "",
Fondateur4: "",

Nom: "Lili Smart",
NombreDeCollaborateurs: "",
Pitch: "Editeur de logiciels pour la santé, Lili smart conçoit des services innovants pour la prévention, l’assistance et l’accompagnement autour du malade et du senior.",
Secteur: "Santé",
SiteWeb: "https://www.lilismart.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Choisissez une approche non médicamenteuse et ludique !",
Email: "hello@lumeen.com",
Fondateur1: "Corentin Metgy",
Fondateur2: "Robin Metgy",
Fondateur3: "Frédéric Cambon",
Fondateur4: "",

Nom: "Lumeen",
NombreDeCollaborateurs: "",
Pitch: "Grâce à une solution de réalité virtuelle adaptée, Lumeen permet aux soignants du grand âge d’organiser des séances de thérapies non médicamenteuses ludiques et motivantes.",
Secteur: "Santé",
SiteWeb: "https://lumeen.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "hugo.b@lx-group.com.au",
Fondateur1: "Hugo Blanc",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",

Nom: "LX Group",
NombreDeCollaborateurs: "",
Pitch: "At LX, we partner with ambitious leaders to create intelligent product ecosystems for a better world. Every day, an accelerating rate of technology change, re-writes everyone’s playbook. In the race to lead, it’s be first or be disrupted. Inventing the future is the best way to be ready for it. Our award winning team and unique IOT Cores platform will help you make transformational ideas real – at scale.",
Secteur: "IoT",
SiteWeb: "https://lx-group.com.au/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "L'innovation pour prévenir les risques de troubles musculo-squelettiques",
Email: "contact@matvisio.com",
Fondateur1: "William Houx-Plantier",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",

Nom: "Matvisio",
NombreDeCollaborateurs: "",
Pitch: "La solution MATVISIO® prévient et réduit les Troubles Musculo-Squelettiques en observant, identifiant et visualisant en temps réel les « postures professionnelles à risques ». Une fois le diagnostic posé, des solutions pragmatiques et opérationnelles sont proposées.",
Secteur: "Santé",
SiteWeb: "http://www.matvisio.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La visite virtuelle comme nouvel outil de travail",
Email: "contact@meilleurevisite.com",
Fondateur1: "Guillaume de Sousa",
Fondateur2: "Thomas Servan",
Fondateur3: "",
Fondateur4: "",

Nom: "Meilleure Visite",
NombreDeCollaborateurs: "",
Pitch: "Nous permettons aux professionnels de l’immobilier de faire de la photo à 360° le nouveau média de l’immobilier et un véritable outil métier, pas un simple outil de communication.",
Secteur: "Immobilier",
SiteWeb: "https://decouvrir.meilleurevisite.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "info@miuros.com",
Fondateur1: "Benoit Gagnon",
Fondateur2: "Ricardo de Aldama",
Fondateur3: "Daniele Alfarone",
Fondateur4: "",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg",
Nom: "Miuros",
NombreDeCollaborateurs: "",
Pitch: "Miuros enables customer service leaders to optimize their operations with the power of AI. Assist your agents so they can increase their efficiency and first reply times. New actionable Insights will help you deliver better customer service so you can improve what actually matters to drive down churn: the overall customer Experience.",
Secteur: "Transformation digitale",
SiteWeb: "https://miuros.com/",
},
{
  BaseLine: "Le print lyonnais mettant en lumière les créateurs et artistes français !",
Email: "contactmoodmagazine.lyon@gmail.com",
Fondateur1: "Andréa Canovas ",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Mood Magazine",
NombreDeCollaborateurs: "",
Pitch: "Mood est un nouveau magazine lyonnais, favorisant la promotion des créateurs et artistes français.  Il est trimestriel et on peut le choper un peu partout dans la ville, dans des concepts store, des ateliers d’artistes, cafés, ou encore lieux émergents. ",
Secteur: "Media",
SiteWeb: "https://www.moodmagazine.fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Vos embouts d'écouteurs imprimés en 3D",
Email: "contact@myfit-solutions.com",
Fondateur1: "Xavier Deshayes",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "MyFit Solutions",
NombreDeCollaborateurs: "",
Pitch: "MyFit Solutions est une startup lyonnaise fondée en 2018 spécialisée dans le développement et la commercialisation d’embouts sur-mesure pour écouteurs de musique. Une oreille, comme une empreinte digitale, est unique. Aussi, chaque embout proposé par MyFit Solutions est défini à partir de 15 points de mesure pris sur chaque oreille. Les embouts sur-mesure, en épousant ainsi parfaitement la forme des oreilles, offrent un maintien absolu.",
Secteur: "E-commerce",
SiteWeb: "https://myfit-solutions.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Des données intelligentes au service de vos objectifs.",
Email: "contact@namr.com",
Fondateur1: "Grégory Labrousse",
Fondateur2: "Emmanuel Bacry",
Fondateur3: "Pierre Lescure",
Fondateur4: "Lila Tretikov",
Nom: "nam.R",
NombreDeCollaborateurs: "",
Pitch: "Nous produisons des données actionnables pour simplifier l’utilisation massive des données externes dans les opérations courantes des entreprises.",
Secteur: "Transformation digitale",
SiteWeb: "https://namr.com/fr/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Play the city",
Email: "hello@neopolisgame.com",
Fondateur1: "Ben Kaltenbaek",
Fondateur2: "Lucas Odion",
Fondateur3: "Roland Lamidieu",
Fondateur4: "",
Nom: "Neopolis",
NombreDeCollaborateurs: "",
Pitch: "Neopolis développe un reality game mobile où les joueurs achètent les bâtiments du monde réel en explorant leur ville. Une rencontre entre Monopoly et Pokemon Go. Notre mission est de transformer le monde en un plateau de jeu géant.",
Secteur: "Gaming",
SiteWeb: "www.neopolisgame.com",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Contextualising Health",
Email: "contact@newclin.com",
Fondateur1: "Pascal Deschaseaux",
Fondateur2: "Dominique Notelet",
Fondateur3: "Bruno Virieux",
Fondateur4: "",
Nom: "Newclin",
NombreDeCollaborateurs: "",
Pitch: "NewClin transforme l’accès aux services de santé via des solutions innovantes basées sur le langage, les technologies et les données. C’est notamment à l’appui des compétences en intelligence artificielle du Laboratoire Hubert Curien (UJM, CNRS) et le soutien de PULSALYS qu’est développée la solution GoClin®.",
Secteur: "Santé",
SiteWeb: "https://www.newclin.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "",
Fondateur1: "Oscar Tellez",
Fondateur2: "Geovanny Osorio",
Fondateur3: "",
Fondateur4: "",
Nom: "NOMAd",
NombreDeCollaborateurs: "",
Pitch: "Nomad, c'est une plateforme web destiné à l'écosystème de personnes à mobilité réduite qui permet à la fois :↵- aux Établissements Sociaux et Medico-Sociaux de réduire le coût transport et améliorer la qualité des services aux personnes↵- aux transporteurs de mieux gérer et optimiser la flotte↵- aux personnes à mobilité réduite de ne pas passer trop de temps dans le transport ou d'attendre longtemps l'arrivée du véhicule.",
Secteur: "Transport & Mobilité",
SiteWeb: "https://nomad.disp-lab.fr/web/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Marque de soins pour hommes noirs et métis",
Email: "contact@oju-wa.com",
Fondateur1: "Mamadou Cissé",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Oju Wa",
NombreDeCollaborateurs: "",
Pitch: "Marque Française de cosmétique pour hommes à la peau noire et métissée, Oju-Wa allie traditions de soin dans un univers contemporain et moderne, fortement influencé par les cultures urbaines.",
Secteur: "E-commerce",
SiteWeb: "https://www.oju-wa.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Le digital pour une mobilité inclusive",
Email: "jeremy@okeenea.com",
Fondateur1: "Sylvain Denonin",
Fondateur2: "Damien Brosseau",
Fondateur3: "",
Fondateur4: "",
Nom: "Okeenea Digital",
NombreDeCollaborateurs: "",
Pitch: "Spinoff du groupe leader en accessibilité éponyme, Okeenea Digital est un fournisseur de services à la mobilité via notamment l’édition d’applications. Okeenea Digital propose des solutions digitales innovantes pour une mobilité inclusive pour toutes les personnes en situation de handicap. C‘est son approche centrée sur l‘usage, la capitalisation sur les 25 ans d‘expérience du groupe et sa capacité à imaginer des dispositifs fiables et scalables qui font la différence.",
Secteur: "Transport & Mobilité",
SiteWeb: "http://www.okeenea-digital.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Ensemble, évitons le gaspillage",
Email: "",
Fondateur1: "Jean Moreau",
Fondateur2: "Baptiste Corval",
Fondateur3: "",
Fondateur4: "",
Nom: "Phenix",
NombreDeCollaborateurs: "",
Pitch: "Un tiers de ce que l’on produit est produit… pour rien. Mais ce n’est pas une fatalité : chez Phenix, nous sommes convaincus que tout déchet peut trouver une seconde vie, pour peu qu’on ait un brin d’imagination.",
Secteur: "Alimentation",
SiteWeb: "https://wearephenix.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Réussisez le concours de vos rêves",
Email: "contact@prepacademy.fr",
Fondateur1: "Xavier Deshayes",
Fondateur2: "Clément Vignal",
Fondateur3: "",
Fondateur4: "",
Nom: "Prepacademy",
NombreDeCollaborateurs: "",
Pitch: "PrepAcademy est un organisme de formation reconnu par l'Etat et spécialisé dans la formation et la préparation aux concours à distance. Nous préparons à 15 formations dont trois en partenariat avec Dunod (éditeur du groupe Hachette). Depuis leur espace, nos élèves bénéficient de tout le contenu pour réviser et d'un accompagnement personnalisé à distance (tutorat, programme de révisions...). En 2 ans, nous avons accompagné plus de 1000 élèves.",
Secteur: "Education",
SiteWeb: "www.prepacademy.fr",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Tous des coureurs",
Email: "",
Fondateur1: "Cécile Chaymol",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Runited",
NombreDeCollaborateurs: "",
Pitch: "RUNited est la premier réseau social dédié à tous les runners. Chez RUNited on pense que chaque coureur est riche de son expérience et qu'il peut être un ressource pour tous les autres : motivation, conseils, générateur d'envie, etc. C'est pourquoi, pour chaque contribution, il gagne des points : des RUNits. Ces points lui permettent d'accéder à des offres proposées par nos partenaires. Ce sont des produits textile, nutrition, services de coaching, abonnements,... Tout le monde est gagnant !",
Secteur: "Sport",
SiteWeb: "",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Le service français d'envoi de (super) gros fichiers.",
Email: "",
Fondateur1: "Romaric Gouedard-Comte",
Fondateur2: "Rémi Gouedard-Comte",
Fondateur3: "Olivier Gouedard-Comte",
Fondateur4: "",
Nom: "Smash",
NombreDeCollaborateurs: "",
Pitch: "Smash, service de transfert de fichiers innovant pour les entreprises de toute taille qui apporte : gain de temps pour les collaborateurs, sécurité/confidentialité pour les DSI et un nouveau canal de communication pour les Directions Générales et Directions de la Communication.",
Secteur: "Transformation digitale",
SiteWeb: "https://fromsmash.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Développer l’engagement de vos collaborateurs",
  Email: "contact@speakup-pulsesurvey.com",
  Fondateur1: "Florian Cordel",
  Fondateur2: "Valentin Kiselak",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "SpeakUP by HPI",
  NombreDeCollaborateurs: "",
  Pitch: "SpeakUP c’est le premier outil RH dédié à la conduite de l’engagement et à la satisfaction de vos collaborateurs. Véritable baromètre social, l’application vous accompagne au quotidien dans vos démarches Qualité de Vie au Travail (QVT).",
  Secteur: "RH",
  SiteWeb: "https://speakup-pulsesurvey.com/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "ERP de l'industrie 4.0",
Email: "service.clients@synktory.fr",
Fondateur1: "Michel Grosjean",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Synktory",
NombreDeCollaborateurs: "",
Pitch: "La société de service informatique externalisée Synktory est une filiale de la société SD Services. Synktory est spécialisé dans le conseil organisationnel, technique et l’intégration de briques logicielles dans le domaine de l'industrie. Synktory a pour cible les PMI et ETI industrielles. Parmi ses clients, notre société compte des entreprises telles que SD Services, son client originel dans le domaine de l'aménagement de véhicules utilitaires sur mesure. SAIRC dans la fabrication et l'affûtage d’outils coupants, MECAL dans la production de métaux, Interscience dans la fabrication de produits d'analyses microbiologiques. Nous assurons aussi un service d'hébergement tel l'ERP de la société Yves Ollivier spécialisé dans l'aménagement de l'espace de travail, ou encore le décisionnel de la société AMETIS qui opère dans l’impression.",
Secteur: "Transformation digitale",
SiteWeb: "https://synktory.com/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Le media culturel et événementiel, 100% vidéo, 100% authentique.",
Email: "contact@teazit.fr",
Fondateur1: "Emilien Colombain",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Teazit",
NombreDeCollaborateurs: "",
Pitch: "Permettre aux organisateurs d’événements de produire et de diffuser en quelques clics un contenu live pour gagner en trafic et en visibilité.",
Secteur: "Media",
SiteWeb: "www.teazit.fr",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "",
Email: "",
Fondateur1: "Martin Hennessey",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "The Writer",
NombreDeCollaborateurs: "",
Pitch: "",
Secteur: "Transformation digitale",
SiteWeb: "",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "La donnée au service de l’investissement immobilier.",
Email: "hello@trackstone.io",
Fondateur1: "Seb de Lavison",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Trackstone",
NombreDeCollaborateurs: "",
Pitch: "Le premier outil d’intelligence immobilière et de « stock picking » pour les professionnels du secteur.",
Secteur: "Immobilier",
SiteWeb: "https://trackstone.io/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
BaseLine: "Agence de design sonore à Lyon",
Email: "contact@tshoko.fr",
Fondateur1: "Hugo Frering",
Fondateur2: "Maxime Meregnani",
Fondateur3: "Raphaël Jarsaillon",
Fondateur4: "",
Nom: "Tshoko",
NombreDeCollaborateurs: "",
Pitch: "L’ambiance d’un établissement doit être maitrisée afin de mettre sa clientèle et ses collaborateurs dans les meilleures dispositions. La musique fait partie de cette équation, Tshoko vous aide à la résoudre simplement.",
Secteur: "Musique",
SiteWeb: "www.tshoko.com",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Maitriser et optimiser votre réseau de transport de voyageurs",
  Email: "contact@ubitransport.com",
  Fondateur1: "Jean-Paul Medioni",
  Fondateur2: "",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Ubitransport",
  NombreDeCollaborateurs: "",
  Pitch: "Leader des Systèmes de Transport Intelligents numériques, Ubitransport propose aux collectivités et opérateurs de gérer leurs réseaux de transport public à partir d’un Smartphone et du Cloud.↵↵Économiquement adaptées à toutes tailles de territoires, les solutions sont en temps réel et livrées clé en main : aide à l’exploitation, billettiques et information voyageurs pour les filières du scolaire, urbain, interurbain et à la demande. Elles permettent de maîtriser, sécuriser et optimiser les réseaux.↵↵Lauréate du Technology Fast 50 et du Grand Prix des Entreprises de Croissance, Ubitransport équipe plus de 120 réseaux en France métropolitaine, Outre-mer et Canada et ambitionne de devenir un acteur global, digital et inclusif de la mobilité.",
  Secteur: "Transport & Mobilité",
  SiteWeb: "https://www.ubitransport.com/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Plus de données, moins de carbone",
Email: "hello@vizcab.io",
Fondateur1: "Guillaume Lafont",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Vizcab",
NombreDeCollaborateurs: "",
Pitch: "Vizcab est la seule solution du marché permettant aux promoteurs et constructeurs de maitriser dès l’amont les ambitions énergie-carbone de leurs projets immobiliers.",
Secteur: "Transition écologique",
SiteWeb: "https://vizcab.io/accueil",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Détection des futurs biens immobiliers à vendre",
  Email: "",
  Fondateur1: "Florian Fenech",
  Fondateur2: "Frédérick Frezzato",
  Fondateur3: "",
  Fondateur4: "",

  Nom: "Volpi Immobilier",
  NombreDeCollaborateurs: "",
  Pitch: "Volpi Immobilier permet aux agents immobiliers de rentrer en contact avec un propriétaire en amont de son projet de vente et avant ses concurrents grâce à une intelligence artificielle.",
  Secteur: "Immobilier",
  SiteWeb: "https://www.volpi-immobilier.fr/",
  Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Nous aidons les entreprises à construire et valoriser leurs engagements contre le réchauffement climatique ",
Email: "antonin@wecount.io",
Fondateur1: "Antonin Guy",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Wecount",
NombreDeCollaborateurs: "",
Pitch: "De nombreuses entreprises souhaitent réduire leur impact CO2 et engager leurs collaborateurs, partenaires et clients dans une transition Bas Carbone. Mais elles ne disposent pas des outils et de l’expertise nécessaires pour construire et mettre en oeuvre une Stratégie Bas Carbone robuste. Notre ambition est de démocratiser la réalisation de Stratégies Bas Carbone par les entreprises en proposant une  solution simple d’utilisation et clé en main.",
Secteur: "Transition écologique",
SiteWeb: "https://www.wecount.io/",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Apprendre. Pratiquer. Jouer.",
Email: "contact@wiplaymusic.com",
Fondateur1: "Eric Magny",
Fondateur2: "Guillaume Cambon",
Fondateur3: "",
Fondateur4: "",
Nom: "Wiplay",
NombreDeCollaborateurs: "",
Pitch: "Un nouvel univers d’apprentissage de la musique, disponible partout : à domicile et dans des lieux partenaires. Laissez-vous guider et apprenez dans le plaisir avec Wiplay music.",
Secteur: "Musique",
SiteWeb: "www.wiplaymusic.com",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"
},
{
  BaseLine: "Who you think running the show?",
Email: "",
Fondateur1: "Léo Devaux",
Fondateur2: "",
Fondateur3: "",
Fondateur4: "",
Nom: "Views",
NombreDeCollaborateurs: "",
Pitch: "Music and lifestyle magazine.",
Secteur: "Media",
SiteWeb: "",
Log: "https://h-7.eu/wp-content/uploads/2020/09/01-1.jpg"

}
  ]

  tab.each do |start| 
    
    StartUp.create(start)
  end
#   BaseLine: start.BaseLine, Email: start.Email, Fondateur1: start.Fondateur1, Fondateur2: start.Fondateur2, Fondateur3: start.Fondateur3, Fondateur4: start.Fondateur4, Nom: start.Nom, Log: start.log, Nombredecollaborateurs: start.Nombredecollaborateurs, Pitch: start.Pitch, Secteur: start.Secteur, SiteWeb: start.SiteWeb)